/** برچسب و راهنمای فارسی فیلدهای تنظیم مدل ۳D نقشه */

export const CATEGORY_MAP_MODEL_FIELD_SECTIONS = [
  {
    id: 'display',
    title: 'نمایش',
    description: 'فعال یا غیرفعال کردن مدل برای این دسته روی نقشه.',
  },
  {
    id: 'size',
    title: 'اندازه و مقیاس',
    description: 'اندازهٔ نمایش مدل روی نقشه و بزرگ‌نمایی/کوچک‌نمایی خود آبجکت.',
  },
  {
    id: 'camera',
    title: 'دوربین و زاویه',
    description: 'زاویهٔ دید دوربین، میدان دید و چرخش اولیهٔ خود مدل (در صورت کج بودن فایل).',
  },
  {
    id: 'light',
    title: 'نور و سایه',
    description: 'روشنایی صحنه و شدت سایهٔ زیر مدل.',
  },
  {
    id: 'motion',
    title: 'حرکت',
    description: 'چرخش خودکار مدل روی نقشه.',
  },
  {
    id: 'upload',
    title: 'فشرده‌سازی آپلود',
    description: 'هنگام آپلود فایل GLB/glTF — پیش‌فرض این دسته. با «ذخیره تنظیمات» ذخیره می‌شود.',
  },
];

export const CATEGORY_MAP_MODEL_FIELDS = {
  enabled: {
    type: 'checkbox',
    section: 'display',
    label: 'نمایش مدل روی نقشه',
    hint: 'اگر غیرفعال باشد، حتی با وجود فایل GLB/glTF، این دسته روی نقشه مارکر سه‌بعدی نشان داده نمی‌شود.',
  },
  sizePx: {
    type: 'number',
    section: 'size',
    label: 'اندازه در نقشه دو‌بعدی (پیکسل)',
    hint: 'عرض و ارتفاع کادر مدل وقتی کاربر نقشه را در حالت ۲D (نمای از بالا) می‌بیند. عدد بزرگ‌تر = مدل درشت‌تر.',
    min: 24,
    max: 200,
    step: 1,
    unit: 'px',
  },
  sizePx3d: {
    type: 'number',
    section: 'size',
    label: 'اندازه در نقشه سه‌بعدی (پیکسل)',
    hint: 'اندازهٔ مدل وقتی نقشه کج شده و حالت ۳D فعال است. معمولاً کمی بزرگ‌تر از ۲D می‌گذارند تا از دور بهتر دیده شود.',
    min: 32,
    max: 240,
    step: 1,
    unit: 'px',
  },
  scale: {
    type: 'number',
    section: 'size',
    label: 'مقیاس آبجکت',
    hint: 'بزرگ یا کوچک کردن خود مدل داخل کادر، بدون تغییر اندازهٔ کادر. ۱ = اندازهٔ اصلی فایل؛ ۱.۲ = ۲۰٪ بزرگ‌تر؛ ۰.۸ = ۲۰٪ کوچک‌تر.',
    min: 0.4,
    max: 2.5,
    step: 0.05,
    unit: '×',
  },
  fieldOfView: {
    type: 'number',
    section: 'camera',
    label: 'میدان دید دوربین (درجه)',
    hint: 'زاویهٔ باز شدن لنز. عدد کمتر = زوم بیشتر و مدل بزرگ‌تر؛ عدد بیشتر = دورتر و مدل کوچک‌تر در کادر.',
    min: 15,
    max: 90,
    step: 1,
    unit: '°',
  },
  cameraOrbit: {
    type: 'text',
    section: 'camera',
    label: 'موقعیت دوربین (Camera orbit)',
    hint: 'زاویهٔ دوربین نسبت به مدل؛ فرمت: «چرخش افقی azimuth» «زاویهٔ ارتفاع polar» «فاصله». مثال پیش‌فرض: 0deg 68deg auto — نمای سه‌ربع از بالا.',
    placeholder: '0deg 68deg auto',
  },
  modelOrientation: {
    type: 'text',
    section: 'camera',
    label: 'چرخش اولیهٔ مدل',
    hint: 'اگر فایل GLB/glTF کج export شده، با سه زاویه (Yaw Pitch Roll) آن را صاف کنید. مثال: 0deg 0deg 0deg یا 0deg 90deg 0deg',
    placeholder: '0deg 0deg 0deg',
  },
  exposure: {
    type: 'number',
    section: 'light',
    label: 'روشنایی (Exposure)',
    hint: 'میزان روشنایی کلی صحنه. کمتر از ۱ = تیره‌تر؛ بیشتر از ۱ = روشن‌تر. برای مدل‌های تیره مقدار را کمی بالا ببرید.',
    min: 0.4,
    max: 2.5,
    step: 0.05,
  },
  shadowIntensity: {
    type: 'number',
    section: 'light',
    label: 'شدت سایه',
    hint: 'قدرت سایهٔ افتاده از مدل. ۰ = بدون سایه؛ ۱ = سایهٔ طبیعی؛ بیشتر = سایهٔ پررنگ‌تر.',
    min: 0,
    max: 2,
    step: 0.05,
  },
  autoRotate: {
    type: 'checkbox',
    section: 'motion',
    label: 'چرخش خودکار',
    hint: 'مدل به‌آرامی دور محور خودش بچرخد تا از همه زاویه دیده شود.',
  },
  rotationPerSecond: {
    type: 'text',
    section: 'motion',
    label: 'سرعت چرخش',
    hint: 'سرعت چرخش خودکار؛ مثلاً 18deg یعنی ۱۸ درجه در ثانیه. برای چرخش آهسته‌تر 10deg و برای سریع‌تر 30deg.',
    placeholder: '18deg',
    showWhen: (form) => form.autoRotate,
  },
  autoRotateDelay: {
    type: 'number',
    section: 'motion',
    label: 'تأخیر قبل از چرخش (میلی‌ثانیه)',
    hint: 'چند میلی‌ثانیه بعد از لود شدن، چرخش خودکار شروع شود. ۰ = بلافاصله.',
    min: 0,
    max: 10000,
    step: 100,
    unit: 'ms',
    showWhen: (form) => form.autoRotate,
  },
  uploadCompressEnabled: {
    type: 'checkbox',
    section: 'upload',
    label: 'فشرده‌سازی هنگام آپلود',
    hint: 'اگر فعال باشد، قبل از ذخیره فایل با glTF Transform بهینه می‌شود. اگر غیرفعال باشد، فایل دقیقاً همان‌طور که آپلود شده ذخیره می‌شود.',
  },
  uploadCompressMode: {
    type: 'select',
    section: 'upload',
    label: 'نوع فشرده‌سازی',
    hint: 'روش فشرده‌سازی را انتخاب کنید. Meshopt متوسط برای اکثر مدل‌های نقشه پیشنهاد می‌شود.',
    showWhen: (form) => form.uploadCompressEnabled,
    optionsKey: 'compressionModes',
    colSpan: 2,
  },
};
