import {
  AcademicCapIcon,
  ArchiveBoxIcon,
  BanknotesIcon,
  BeakerIcon,
  BoltIcon,
  BookOpenIcon,
  BuildingLibraryIcon,
  BuildingOffice2Icon,
  BuildingStorefrontIcon,
  ArrowsRightLeftIcon,
  CameraIcon,
  CloudIcon,
  CreditCardIcon,
  DevicePhoneMobileIcon,
  FireIcon,
  FlagIcon,
  GlobeAltIcon,
  GlobeAmericasIcon,
  HeartIcon,
  HomeIcon,
  HomeModernIcon,
  KeyIcon,
  MapPinIcon,
  MoonIcon,
  MusicalNoteIcon,
  PaperAirplaneIcon,
  PhoneIcon,
  PresentationChartLineIcon,
  RectangleStackIcon,
  ShieldCheckIcon,
  ShoppingBagIcon,
  SparklesIcon,
  SunIcon,
  TicketIcon,
  TrophyIcon,
  TruckIcon,
  UserGroupIcon,
  VideoCameraIcon,
  WrenchScrewdriverIcon,
} from '@heroicons/react/24/outline';
import { PLACE_CATEGORY_CUSTOM_ICONS } from './placeCategoryIcons';

export const MAP_PLACE_CATEGORY_ICON_MAP = {
  ...PLACE_CATEGORY_CUSTOM_ICONS,
  HeartIcon,
  ShieldCheckIcon,
  BuildingLibraryIcon,
  BanknotesIcon,
  AcademicCapIcon,
  MoonIcon,
  TruckIcon,
  BoltIcon,
  RectangleStackIcon,
  GlobeAmericasIcon,
  SparklesIcon,
  TrophyIcon,
  ShoppingBagIcon,
  MapPinIcon,
  BuildingOffice2Icon,
  HomeModernIcon,
  BeakerIcon,
  ClipboardDocumentListIcon: PresentationChartLineIcon,
  WrenchScrewdriverIcon,
  FireIcon,
  PhoneIcon,
  UserGroupIcon,
  FlagIcon,
  ArchiveBoxIcon,
  DevicePhoneMobileIcon,
  KeyIcon,
  CreditCardIcon,
  BookOpenIcon,
  SunIcon,
  BusIcon: TruckIcon,
  TrainIcon: ArrowsRightLeftIcon,
  PaperAirplaneIcon,
  GlobeAltIcon,
  TicketIcon,
  CameraIcon,
  VideoCameraIcon,
  MusicalNoteIcon,
  BuildingStorefrontIcon,
  HomeIcon,
  CloudIcon,
};

/** @typedef {{ id: string; title: string; term?: string; icon: keyof typeof MAP_PLACE_CATEGORY_ICON_MAP }} MapPlaceSubCategory */
/** عبارت جستجو: mapPlaceSearchTerms.js — title فقط برای نمایش UI */
/** @typedef {{ id: string; title: string; icon: keyof typeof MAP_PLACE_CATEGORY_ICON_MAP; tone: string; items: MapPlaceSubCategory[] }} MapPlaceMainCategory */

/** @type {MapPlaceMainCategory[]} */
export const MAP_PLACE_CATEGORIES = [
  {
    id: 'medical',
    title: 'مراکز درمانی',
    icon: 'PlaceMedicalCategoryIcon',
    tone: 'rose',
    items: [
      { id: 'hospital', title: 'بیمارستان', term: 'بیمارستان', icon: 'PlaceHospitalIcon' },
      { id: 'clinic-center', title: 'درمانگاه', term: 'درمانگاه', icon: 'PlaceClinicIcon' },
      { id: 'clinic', title: 'کلینیک', term: 'کلینیک', icon: 'PlaceClinicIcon' },
      { id: 'pharmacy', title: 'داروخانه', term: 'داروخانه', icon: 'PlacePharmacyIcon' },
      { id: 'lab', title: 'آزمایشگاه', term: 'آزمایشگاه', icon: 'PlaceLabIcon' },
      { id: 'radiology', title: 'رادیولوژی', term: 'رادیولوژی', icon: 'CameraIcon' },
      { id: 'physio', title: 'فیزیوتراپی', term: 'فیزیوتراپی', icon: 'WrenchScrewdriverIcon' },
      { id: 'emergency', title: 'اورژانس', term: 'اورژانس', icon: 'PlaceEmergencyIcon' },
      { id: 'blood', title: 'پایگاه انتقال خون', term: 'انتقال خون', icon: 'PlaceBloodIcon' },
    ],
  },
  {
    id: 'security',
    title: 'مراکز امنیتی و امدادی',
    icon: 'PlaceSecurityCategoryIcon',
    tone: 'amber',
    items: [
      { id: 'fire', title: 'آتش‌نشانی', term: 'آتش نشانی', icon: 'PlaceFireTruckIcon' },
      { id: 'police-station', title: 'کلانتری', term: 'کلانتری', icon: 'PlacePoliceIcon' },
      { id: 'police-post', title: 'پاسگاه', term: 'پاسگاه', icon: 'PlacePoliceIcon' },
      { id: 'traffic-police', title: 'پلیس راهور', term: 'پلیس راهور', icon: 'PlacePoliceIcon' },
      { id: 'police-110', title: 'پلیس +۱۰', term: 'پلیس', icon: 'PhoneIcon' },
      { id: 'red-crescent', title: 'هلال احمر', term: 'هلال احمر', icon: 'PlaceBloodIcon' },
      { id: 'crisis', title: 'مدیریت بحران', term: 'مدیریت بحران', icon: 'FlagIcon' },
      { id: 'roadside', title: 'امداد خودرو', term: 'امداد خودرو', icon: 'TruckIcon' },
    ],
  },
  {
    id: 'government',
    title: 'مراکز دولتی',
    icon: 'PlaceGovernmentIcon',
    tone: 'slate',
    items: [
      { id: 'municipality', title: 'شهرداری', term: 'شهرداری', icon: 'PlaceGovernmentIcon' },
      { id: 'governor', title: 'فرمانداری', term: 'فرمانداری', icon: 'BuildingOffice2Icon' },
      { id: 'district', title: 'بخشداری', term: 'بخشداری', icon: 'BuildingOffice2Icon' },
      { id: 'ostandar', title: 'استانداری', term: 'استانداری', icon: 'BuildingOffice2Icon' },
      { id: 'post', title: 'اداره پست', term: 'اداره پست', icon: 'ArchiveBoxIcon' },
      { id: 'civil-reg', title: 'ثبت احوال', term: 'ثبت احوال', icon: 'ArchiveBoxIcon' },
      { id: 'deed-reg', title: 'ثبت اسناد', term: 'ثبت اسناد', icon: 'ArchiveBoxIcon' },
      { id: 'tax', title: 'اداره مالیات', term: 'اداره مالیات', icon: 'BanknotesIcon' },
      { id: 'labor', title: 'اداره کار', term: 'اداره کار', icon: 'UserGroupIcon' },
      { id: 'power', title: 'اداره برق', term: 'اداره برق', icon: 'BoltIcon' },
      { id: 'water', title: 'اداره آب', term: 'اداره آب', icon: 'CloudIcon' },
      { id: 'gas', title: 'اداره گاز', term: 'اداره گاز', icon: 'FireIcon' },
      { id: 'telecom', title: 'اداره مخابرات', term: 'مخابرات', icon: 'DevicePhoneMobileIcon' },
      { id: 'egov', title: 'دفاتر خدمات الکترونیک', term: 'دفتر خدمات', icon: 'DevicePhoneMobileIcon' },
    ],
  },
  {
    id: 'financial',
    title: 'مراکز مالی',
    icon: 'PlaceBankIcon',
    tone: 'emerald',
    items: [
      { id: 'bank', title: 'بانک', term: 'بانک', icon: 'PlaceBankIcon' },
      { id: 'atm', title: 'خودپرداز', term: 'خودپرداز', icon: 'PlaceAtmIcon' },
      { id: 'exchange', title: 'صرافی', term: 'صرافی', icon: 'BanknotesIcon' },
      { id: 'insurance', title: 'بیمه', term: 'بیمه', icon: 'ShieldCheckIcon' },
      { id: 'loan', title: 'صندوق قرض‌الحسنه', term: 'قرض الحسنه', icon: 'BanknotesIcon' },
    ],
  },
  {
    id: 'education',
    title: 'مراکز آموزشی',
    icon: 'AcademicCapIcon',
    tone: 'blue',
    items: [
      { id: 'kindergarten', title: 'مهدکودک', term: 'مهدکودک', icon: 'SparklesIcon' },
      { id: 'school', title: 'مدرسه', term: 'مدرسه', icon: 'PlaceSchoolIcon' },
      { id: 'highschool', title: 'دبیرستان', term: 'دبیرستان', icon: 'PlaceSchoolIcon' },
      { id: 'vocational', title: 'هنرستان', term: 'هنرستان', icon: 'WrenchScrewdriverIcon' },
      { id: 'university', title: 'دانشگاه', term: 'دانشگاه', icon: 'PlaceUniversityIcon' },
      { id: 'institute', title: 'آموزشگاه', term: 'آموزشگاه', icon: 'BookOpenIcon' },
      { id: 'library', title: 'کتابخانه', term: 'کتابخانه', icon: 'BookOpenIcon' },
    ],
  },
  {
    id: 'religious',
    title: 'مراکز مذهبی',
    icon: 'PlaceReligiousCategoryIcon',
    tone: 'violet',
    items: [
      { id: 'mosque', title: 'مسجد', term: 'مسجد', icon: 'PlaceMosqueIcon' },
      { id: 'husseiniya', title: 'حسینیه', term: 'حسینیه', icon: 'PlaceHusseiniyaIcon' },
      { id: 'imamzadeh', title: 'امامزاده', term: 'امامزاده', icon: 'PlaceMosqueIcon' },
      { id: 'musalla', title: 'مصلی', term: 'مصلی', icon: 'PlaceMosqueIcon' },
      { id: 'seminary', title: 'حوزه علمیه', term: 'حوزه علمیه', icon: 'BookOpenIcon' },
      { id: 'cemetery', title: 'آرامستان / قبرستان', term: 'قبرستان', icon: 'PlaceCemeteryIcon' },
    ],
  },
  {
    id: 'transport',
    title: 'حمل و نقل',
    icon: 'PlaceTransportCategoryIcon',
    tone: 'cyan',
    items: [
      { id: 'airport', title: 'فرودگاه', term: 'فرودگاه', icon: 'PlaceAirportIcon' },
      { id: 'train-station', title: 'ایستگاه قطار', term: 'ایستگاه قطار', icon: 'PlaceTrainIcon' },
      { id: 'rail', title: 'راه‌آهن', term: 'راه آهن', icon: 'PlaceTrainIcon' },
      { id: 'metro', title: 'مترو', term: 'مترو', icon: 'PlaceMetroIcon' },
      { id: 'metro-station', title: 'ایستگاه مترو', term: 'ایستگاه مترو', icon: 'PlaceMetroIcon' },
      { id: 'terminal', title: 'ترمینال مسافربری', term: 'ترمینال', icon: 'PlaceBusIcon' },
      { id: 'bus-station', title: 'ایستگاه اتوبوس', term: 'ایستگاه اتوبوس', icon: 'PlaceBusIcon' },
      { id: 'taxi', title: 'ایستگاه تاکسی', term: 'ایستگاه تاکسی', icon: 'PlaceTaxiIcon' },
      { id: 'pier', title: 'اسکله', term: 'اسکله', icon: 'PlacePortIcon' },
      { id: 'port', title: 'بندر', term: 'بندر', icon: 'PlacePortIcon' },
    ],
  },
  {
    id: 'fuel',
    title: 'سوخت و انرژی',
    icon: 'PlaceFuelCategoryIcon',
    tone: 'orange',
    items: [
      { id: 'gas-station', title: 'پمپ بنزین', term: 'پمپ بنزین', icon: 'PlaceGasPumpIcon' },
      { id: 'cng', title: 'جایگاه CNG', term: 'CNG', icon: 'PlaceCngIcon' },
      { id: 'ev-charge', title: 'ایستگاه شارژ خودرو برقی', term: 'شارژ خودرو', icon: 'PlaceEvChargeIcon' },
    ],
  },
  {
    id: 'parking',
    title: 'پارکینگ و تردد',
    icon: 'PlaceParkingIcon',
    tone: 'stone',
    items: [
      { id: 'parking', title: 'پارکینگ عمومی', term: 'پارکینگ', icon: 'PlaceParkingIcon' },
      { id: 'parking-multi', title: 'پارکینگ طبقاتی', term: 'پارکینگ طبقاتی', icon: 'BuildingOffice2Icon' },
      { id: 'parking-247', title: 'پارکینگ شبانه‌روزی', term: 'پارکینگ', icon: 'KeyIcon' },
      { id: 'toll', title: 'عوارضی', term: 'عوارضی', icon: 'TicketIcon' },
      { id: 'inspection', title: 'مرکز معاینه فنی', term: 'معاینه فنی', icon: 'WrenchScrewdriverIcon' },
    ],
  },
  {
    id: 'public',
    title: 'اماکن عمومی',
    icon: 'PlacePublicCategoryIcon',
    tone: 'lime',
    items: [
      { id: 'park', title: 'پارک', term: 'پارک', icon: 'PlaceParkIcon' },
      { id: 'garden', title: 'بوستان', term: 'بوستان', icon: 'PlaceParkIcon' },
      { id: 'green-space', title: 'فضای سبز', term: 'فضای سبز', icon: 'PlaceParkIcon' },
      { id: 'square', title: 'میدان', term: 'میدان', icon: 'MapPinIcon' },
      { id: 'beach', title: 'ساحل', term: 'ساحل', icon: 'PlaceBeachIcon' },
      { id: 'recreation', title: 'تفرجگاه', term: 'تفرجگاه', icon: 'SunIcon' },
      { id: 'waterfall', title: 'آبشار', term: 'آبشار', icon: 'CloudIcon' },
      { id: 'lake', title: 'دریاچه', term: 'دریاچه', icon: 'CloudIcon' },
      { id: 'mountain', title: 'کوهستان', term: 'کوهستان', icon: 'PlaceMountainIcon' },
      { id: 'forest', title: 'جنگل', term: 'جنگل', icon: 'PlaceParkIcon' },
    ],
  },
  {
    id: 'culture',
    title: 'مراکز فرهنگی',
    icon: 'PlaceCultureCategoryIcon',
    tone: 'purple',
    items: [
      { id: 'culture-center', title: 'فرهنگسرا', term: 'فرهنگسرا', icon: 'SparklesIcon' },
      { id: 'cinema', title: 'سینما', term: 'سینما', icon: 'PlaceCinemaIcon' },
      { id: 'theater', title: 'تئاتر', term: 'تئاتر', icon: 'MusicalNoteIcon' },
      { id: 'museum', title: 'موزه', term: 'موزه', icon: 'PlaceMuseumIcon' },
      { id: 'gallery', title: 'نگارخانه', term: 'نگارخانه', icon: 'CameraIcon' },
      { id: 'house-of-culture', title: 'خانه فرهنگ', term: 'خانه فرهنگ', icon: 'HomeIcon' },
    ],
  },
  {
    id: 'sports',
    title: 'مراکز ورزشی',
    icon: 'PlaceSportsCategoryIcon',
    tone: 'teal',
    items: [
      { id: 'stadium', title: 'ورزشگاه', term: 'ورزشگاه', icon: 'PlaceStadiumIcon' },
      { id: 'gym', title: 'باشگاه ورزشی', term: 'باشگاه ورزشی', icon: 'TrophyIcon' },
      { id: 'pool', title: 'استخر', term: 'استخر', icon: 'PlacePoolIcon' },
      { id: 'sport-hall', title: 'سالن ورزشی', term: 'سالن ورزشی', icon: 'PlaceStadiumIcon' },
      { id: 'football', title: 'زمین فوتبال', term: 'زمین فوتبال', icon: 'TrophyIcon' },
      { id: 'tennis', title: 'زمین تنیس', term: 'زمین تنیس', icon: 'TrophyIcon' },
    ],
  },
  {
    id: 'shopping',
    title: 'مراکز خرید',
    icon: 'PlaceShoppingIcon',
    tone: 'pink',
    items: [
      { id: 'passage', title: 'پاساژ', term: 'پاساژ', icon: 'PlaceShoppingIcon' },
      { id: 'mall', title: 'مجتمع تجاری', term: 'مجتمع تجاری', icon: 'BuildingStorefrontIcon' },
      { id: 'bazaar', title: 'بازار', term: 'بازار', icon: 'PlaceBazaarIcon' },
      { id: 'bazaarche', title: 'بازارچه', term: 'بازارچه', icon: 'PlaceBazaarIcon' },
      { id: 'shopping-center', title: 'مرکز خرید', term: 'مرکز خرید', icon: 'BuildingStorefrontIcon' },
    ],
  },
  {
    id: 'tourism',
    title: 'اقامت و گردشگری',
    icon: 'PlaceTourismCategoryIcon',
    tone: 'indigo',
    items: [
      { id: 'hotel', title: 'هتل', term: 'هتل', icon: 'PlaceHotelIcon' },
      { id: 'apart-hotel', title: 'هتل آپارتمان', term: 'هتل آپارتمان', icon: 'HomeModernIcon' },
      { id: 'guesthouse', title: 'مهمان‌پذیر', term: 'مهمانپذیر', icon: 'HomeIcon' },
      { id: 'ecolodge', title: 'اقامتگاه بومگردی', term: 'بومگردی', icon: 'HomeIcon' },
      { id: 'camp', title: 'کمپ', term: 'کمپ', icon: 'PlaceParkIcon' },
      { id: 'travel-agency', title: 'آژانس مسافرتی', term: 'آژانس مسافرتی', icon: 'PlaceTravelAgencyIcon' },
    ],
  },
];

export const MAP_PLACE_CATEGORY_TONE_STYLES = {
  rose: {
    chip: 'bg-rose-50 text-rose-800 ring-rose-200/80',
    icon: 'bg-rose-100 text-rose-600',
    active: 'border-rose-400 bg-rose-50 ring-rose-300/70',
    activeIcon: 'bg-rose-600 text-white',
  },
  amber: {
    chip: 'bg-amber-50 text-amber-900 ring-amber-200/80',
    icon: 'bg-amber-100 text-amber-700',
    active: 'border-amber-400 bg-amber-50 ring-amber-300/70',
    activeIcon: 'bg-amber-600 text-white',
  },
  slate: {
    chip: 'bg-slate-100 text-slate-800 ring-slate-200/80',
    icon: 'bg-slate-200 text-slate-700',
    active: 'border-slate-400 bg-slate-50 ring-slate-300/70',
    activeIcon: 'bg-slate-700 text-white',
  },
  emerald: {
    chip: 'bg-emerald-50 text-emerald-800 ring-emerald-200/80',
    icon: 'bg-emerald-100 text-emerald-700',
    active: 'border-emerald-400 bg-emerald-50 ring-emerald-300/70',
    activeIcon: 'bg-emerald-600 text-white',
  },
  blue: {
    chip: 'bg-blue-50 text-blue-800 ring-blue-200/80',
    icon: 'bg-blue-100 text-blue-700',
    active: 'border-blue-400 bg-blue-50 ring-blue-300/70',
    activeIcon: 'bg-blue-600 text-white',
  },
  violet: {
    chip: 'bg-violet-50 text-violet-800 ring-violet-200/80',
    icon: 'bg-violet-100 text-violet-700',
    active: 'border-violet-400 bg-violet-50 ring-violet-300/70',
    activeIcon: 'bg-violet-600 text-white',
  },
  cyan: {
    chip: 'bg-cyan-50 text-cyan-900 ring-cyan-200/80',
    icon: 'bg-cyan-100 text-cyan-700',
    active: 'border-cyan-400 bg-cyan-50 ring-cyan-300/70',
    activeIcon: 'bg-cyan-600 text-white',
  },
  orange: {
    chip: 'bg-orange-50 text-orange-900 ring-orange-200/80',
    icon: 'bg-orange-100 text-orange-700',
    active: 'border-orange-400 bg-orange-50 ring-orange-300/70',
    activeIcon: 'bg-orange-600 text-white',
  },
  stone: {
    chip: 'bg-stone-100 text-stone-800 ring-stone-200/80',
    icon: 'bg-stone-200 text-stone-700',
    active: 'border-stone-400 bg-stone-50 ring-stone-300/70',
    activeIcon: 'bg-stone-600 text-white',
  },
  lime: {
    chip: 'bg-lime-50 text-lime-900 ring-lime-200/80',
    icon: 'bg-lime-100 text-lime-800',
    active: 'border-lime-500 bg-lime-50 ring-lime-300/70',
    activeIcon: 'bg-lime-600 text-white',
  },
  purple: {
    chip: 'bg-purple-50 text-purple-800 ring-purple-200/80',
    icon: 'bg-purple-100 text-purple-700',
    active: 'border-purple-400 bg-purple-50 ring-purple-300/70',
    activeIcon: 'bg-purple-600 text-white',
  },
  teal: {
    chip: 'bg-teal-50 text-teal-800 ring-teal-200/80',
    icon: 'bg-teal-100 text-teal-700',
    active: 'border-teal-400 bg-teal-50 ring-teal-300/70',
    activeIcon: 'bg-teal-600 text-white',
  },
  pink: {
    chip: 'bg-pink-50 text-pink-800 ring-pink-200/80',
    icon: 'bg-pink-100 text-pink-700',
    active: 'border-pink-400 bg-pink-50 ring-pink-300/70',
    activeIcon: 'bg-pink-600 text-white',
  },
  indigo: {
    chip: 'bg-indigo-50 text-indigo-800 ring-indigo-200/80',
    icon: 'bg-indigo-100 text-indigo-700',
    active: 'border-indigo-400 bg-indigo-50 ring-indigo-300/70',
    activeIcon: 'bg-indigo-600 text-white',
  },
};

export function resolvePlaceCategoryIcon(name) {
  return MAP_PLACE_CATEGORY_ICON_MAP[name] || MapPinIcon;
}
